
labels_original:
  0: "unlabeled"
  1: "Smoke"
  2: "Exhaust"
  3: "Spray or rain"
  4: "Reflection"
  5: "Vegetation"
  6: "Ground"
  7: "Road"
  8: "Lane Line Marking"
  9: "Stop Line Marking"
  10: "Other Road Marking"
  11: "Sidewalk"
  12: "Driveway"
  13: "Car"
  14: "Pickup Truck"
  15: "Medium-sized Truck"
  16: "Semi-truck"
  17: "Towed Object"
  18: "Motorcycle"
  19: "Other Vehicle - Construction Vehicle"
  20: "Other Vehicle - Uncommon"
  21: "Other Vehicle - Pedicab"
  22: "Emergency Vehicle"
  23: "Bus"
  24: "Personal Mobility Device"
  25: "Motorized Scooter"
  26: "Bicycle"
  27: "Train"
  28: "Trolley"
  29: "Tram / Subway"
  30: "Pedestrian"
  31: "Pedestrian with Object"
  32: "Animals - Bird"
  33: "Animals - Other"
  34: "Pylons"
  35: "Road Barriers"
  36: "Signs"
  37: "Cones"
  38: "Construction Signs"
  39: "Temporary Construction Barriers"
  40: "Rolling Containers"
  41: "Building"
  42: "Other Static Object"

# Select any number of labels for training. Originally there are 42 labels in Pandaset.
# So all 42 labels or specific labels can be selected for training.
labels:
  0: "unlabeled"
  1: "Car"
  2: "Bus"
  3: "Ground"
  4: "Road"
  5: "Pickup Truck"
  6: "Motorcycle"
  7: "Train"
  8: "Building"
  9: "Trolley"
  10: "Rolling Containers"
  11: "Other Static Object"

# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent

learning_map:
  0: 0
  1: 0
  2: 0
  3: 0
  4: 0
  5: 3
  6: 3
  7: 4
  8: 0
  9: 0
  10: 0
  11: 4
  12: 4
  13: 1
  14: 5
  15: 5
  16: 5
  17: 11
  18: 6
  19: 5
  20: 5
  21: 5
  22: 2
  23: 2
  24: 11
  25: 6
  26: 6
  27: 7
  28: 9
  29: 7
  30: 11
  31: 11
  32: 11
  33: 11
  34: 11
  35: 11
  36: 0
  37: 0
  38: 0
  39: 11
  40: 10
  41: 8
  42: 11

color_map: # bgr
  0 : [0, 0, 0]
  1 : [200, 0, 10]
  2 : [0, 0, 255]
  3: [245, 150, 100]
  4: [245, 230, 100]
  5: [250, 80, 100]
  6: [150, 60, 30]
  7: [255, 0, 0]
  8: [180, 30, 80]
  9: [255, 0, 0]
  10: [30, 30, 255]
  11: [200, 40, 255]
  12: [90, 30, 150]
  13: [255, 0, 255]
  14: [255, 150, 255]
  15: [75, 0, 75]
  16: [75, 0, 175]
  17: [0, 200, 255]
  18: [50, 120, 255]
  19: [0, 150, 255]
  20: [170, 255, 150]
  21: [0, 175, 0]
  22: [0, 60, 135]
  23: [80, 240, 150]
  24: [150, 240, 255]
  25: [0, 0, 255]
  26: [255, 255, 50]
  27: [245, 150, 100]
  28: [255, 0, 0]
  29: [200, 40, 255]
  30: [30, 30, 255]
  31: [90, 30, 150]
  32: [250, 80, 100]
  33: [180, 30, 80]
  34: [255, 0, 0]
  35: [155, 255, 50]
  36: [45, 150, 100]
  37: [25, 0, 0]
  38: [20, 40, 255]
  39: [130, 30, 255]
  40: [190, 30, 150]
  41: [25, 80, 100]
  42: [18, 30, 80]

split: # sequence numbers
  train:
    - 1
    - 2
    - 3
    - 5
    - 11
    - 13
    - 15
    - 16
    - 17
    - 21
    - 23
    - 24
    - 27
    - 28
    - 29
    - 30
    - 95
    - 97
    - 98
    - 19
    - 32
    - 33
    - 34
    - 35
    - 37
    - 38
    - 39
    - 66
    - 78
    - 40
    - 41
    - 42
    - 43
    - 44
    - 46
    - 52
    - 53
    - 54
    - 56
    - 57
    - 58
    - 64
    - 65
    - 67
    - 69
    - 70
    - 71
    - 72
    - 73
    - 77
    - 80
    - 84
    - 88
    - 89
    - 90
    - 94
  valid:
    - 101
    - 102
    - 103
    - 105
    - 106
    - 109
    - 110
  test:
    - 112
    - 113
    - 115
    - 116
    - 117
    - 119
    - 120
    - 122
    - 123
    - 124
    - 139
    - 149
    - 158
    